# Script para corregir problemas de codificación en index.html
$filePath = "C:\xampp\htdocs\Musa\index.html"

# Leer el contenido del archivo
$content = Get-Content -Path $filePath -Raw

# Definir las correcciones necesarias
$replacements = @{
    "producci�n" = "producción"
    "t�tulo" = "título"
    "escribir�" = "escribirá"
    "Funci�n" = "Función"
    "funci�n" = "función"
    "despu�s" = "después"
    "p�gina" = "página"
    "env�o" = "envío"
    "v�lido" = "válido"
    "navegaci�n" = "navegación"
    "g�nero" = "género"
    "categor�a" = "categoría"
    "categor�as" = "categorías"
    "Bot�n" = "Botón"
    "Men�" = "Menú"
    "men�" = "menú"
    "COLECCI�N" = "COLECCIÓN"
    "l�nea" = "línea"
    "Administraci�n" = "Administración"
    "b�squeda" = "búsqueda"
    "B�squeda" = "Búsqueda"
    "l�gica" = "lógica"
    "aqu�" = "aquí"
    "art�culos" = "artículos"
    "din�micos" = "dinámicos"
    "Env�o" = "Envío"
    "Verificaci�n" = "Verificación"
    "verificaci�n" = "verificación"
    "informaci�n" = "información"
    "selecci�n" = "selección"
    "direcci�n" = "dirección"
    "tel�fono" = "teléfono"
    "env�os" = "envíos"
    "cr�dito" = "crédito"
    "d�bito" = "débito"
    "identificaci�n" = "identificación"
    "terminaci�n" = "terminación"
    "confirmaci�n" = "confirmación"
    "transacci�n" = "transacción"
    "descripci�n" = "descripción"
    "protecci�n" = "protección"
    "autenticaci�n" = "autenticación"
    "configuraci�n" = "configuración"
    "notificaci�n" = "notificación"
    "validaci�n" = "validación"
    "gesti�n" = "gestión"
    "soluci�n" = "solución"
    "creaci�n" = "creación"
    "modificaci�n" = "modificación"
    "eliminaci�n" = "eliminación"
    "c�digo" = "código"
    "c�digos" = "códigos"
    "l�mite" = "límite"
    "n�mero" = "número"
    "n�meros" = "números"
    "m�s" = "más"
    "tama�o" = "tamaño"
    "tama�os" = "tamaños"
    "dise�o" = "diseño"
    "dise�os" = "diseños"
    "a�o" = "año"
    "a�os" = "años"
    "rese�a" = "reseña"
    "rese�as" = "reseñas"
    "peque�o" = "pequeño"
    "peque�a" = "pequeña"
    "peque�os" = "pequeños"
    "peque�as" = "pequeñas"
    "espa�ol" = "español"
    "espa�ola" = "española"
    "ni�o" = "niño"
    "ni�a" = "niña"
    "ni�os" = "niños"
    "ni�as" = "niñas"
    "sue�o" = "sueño"
    "sue�os" = "sueños"
    "oto�o" = "otoño"
    "m�nimo" = "mínimo"
    "m�nima" = "mínima"
    "m�ximo" = "máximo"
    "m�xima" = "máxima"
    "cl�sico" = "clásico"
    "cl�sica" = "clásica"
    "b�sico" = "básico"
    "b�sica" = "básica"
    "hist�rico" = "histórico"
    "hist�rica" = "histórica"
    "econ�mico" = "económico"
    "econ�mica" = "económica"
    "autom�tico" = "automático"
    "autom�tica" = "automática"
    "din�mico" = "dinámico"
    "din�mica" = "dinámica"
    "sistem�tico" = "sistemático"
    "sistem�tica" = "sistemática"
    "peri�dico" = "periódico"
    "peri�dica" = "periódica"
    "espec�fico" = "específico"
    "espec�fica" = "específica"
    "caracter�stica" = "característica"
    "caracter�sticas" = "características"
    "farmac�utico" = "farmacéutico"
    "farmac�utica" = "farmacéutica"
    "m�dico" = "médico"
    "m�dica" = "médica"
    "qu�mico" = "químico"
    "qu�mica" = "química"
    "f�sico" = "físico"
    "f�sica" = "física"
    "m�sico" = "músico"
    "m�sica" = "música"
    "art�stico" = "artístico"
    "art�stica" = "artística"
    "pol�tico" = "político"
    "pol�tica" = "política"
    "jur�dico" = "jurídico"
    "jur�dica" = "jurídica"
    "acad�mico" = "académico"
    "acad�mica" = "académica"
    "pr�ctico" = "práctico"
    "pr�ctica" = "práctica"
    "te�rico" = "teórico"
    "te�rica" = "teórica"
    "emp�rico" = "empírico"
    "emp�rica" = "empírica"
    "met�dico" = "metódico"
    "met�dica" = "metódica"
}

# Aplicar todas las correcciones
foreach ($old in $replacements.Keys) {
    $new = $replacements[$old]
    $content = $content -replace [regex]::Escape($old), $new
    Write-Host "Corrigiendo: $old -> $new"
}

# Guardar el archivo corregido
Set-Content -Path $filePath -Value $content -Encoding UTF8
Write-Host "Archivo corregido y guardado con codificación UTF-8"
